# Generated by Django 5.1.7 on 2025-04-25 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='deductions',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='gross_salary',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='net_salary',
        ),
    ]
