# Generated by Django 5.1.7 on 2025-04-25 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_payroll_deductions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deductions',
            name='total_deductions',
        ),
    ]
